name: mimiciv-tabular
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2.2
  - pyarrow=16.1.0
  - sqlalchemy=2.0.31
  - duckdb=1.0.0           
  - psycopg2=2.9.9
  - jupyterlab=4.2.5
  - ipykernel=6.29.5
  - python-dotenv=1.0.1
  - matplotlib=3.8.4
  - pip
  - openpyxl
  - tableone
  - pip:
      - google-cloud-bigquery==3.25.0
      - google-cloud-bigquery-storage==2.25.0
      - db-dtypes==1.3.0
      - ydata-profiling==4.6.0